name: Build Page

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vitepress
        run: npm install vitepress

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Wulian233/vmct-website-beta
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm run build
          BUILD_DIR: .vitepress/dist/