name: Build Page

on:
  push:
    paths-ignore:
      - 'readme.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vitepress
        run: npm install vitepress

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@v1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Wulian233/vmct-website-beta
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm run build
          BUILD_DIR: .vitepress/dist/